const ProblemList =
[
  EquacaoNL(x -> 3x - 5, 1.0, "Linear"),
  EquacaoNL(x -> x^2 - 2, 1.0, "Raiz de 2"),
  EquacaoNL(x -> exp(x) - 2, log(2), "Exp"),
  EquacaoNL(x -> x * log(x^2 + 1) - 2, 1.588288847, "Log"),
  EquacaoNL(x -> x * exp(x) - 1, 1.0, "Omega"),
  EquacaoNL(x -> x^3 - 2^3, 1.0, 2.0, "Cubico"),
  EquacaoNL(x -> x^4 - 2^4, 1.0, 2.0, "Quádrica"),
  EquacaoNL(x -> x^5 - 2^5, 1.0, 2.0, "Grau 5"),
  EquacaoNL(x -> sin(x) + max(3 - x, 0)^2 + max(x - 3.2, 0)^2, 1.0, "π por sin"),
  EquacaoNL(x -> 1 / (1 + exp(-0.1x + 1)) - 0.5, 0.0, "Sigmoid"),
  EquacaoNL(x -> x^6 - 48*x^4 + 1344*x^2 -4096, 0.0,"Grau 6"),
  EquacaoNL(x -> sin(exp(x))+cos(exp(x)), 0.0,"sen + cos de exp"),
  EquacaoNL(x -> (x - π/2)*sin(x - π/2), 0.0,"x sen x"),
  EquacaoNL(x -> (x + π) + (x + π)*cos(x + π), 0.0,"Cos transladado"),
  EquacaoNL(x -> sin(x - ℯ)/exp(x), 0.0,"Sen por exp"),
  EquacaoNL(x -> 1e6*cos(x), 0.0,"Cos grande amplitude"),
  EquacaoNL(x -> cos(1e6*x), 0.0,"Cos período pequeno"),
  EquacaoNL(x -> 1e-6*cos(x), 0.0,"Cos pequena amplitude"),
  EquacaoNL(x -> sin(x + ℯ)*cos(x - ℯ), 0.0,"sen cos"),
  EquacaoNL(x -> exp(x)*sin(x + π/2), 0.0,"Sen vezes exp"),
]
